### PR TITLE
Parquet read failing test case

### PR DESCRIPTION
**Pull request by thinkharderdev**
Looks like parquet sources don't produce any data when scheduled. This is a test case which reproduces.

### CODE REVIEW

**Comment by tustvold** [comment]
Thank you for the report, I'm afraid I am away from a computer the next couple of days but I'll take a look when I get back.

That being said, my hunch is that the test is panicking somewhere, and this is getting lost as the log facade isn't initialised. Perhaps you might test this out?

**Comment by thinkharderdev** [comment]
> Thank you for the report, I'm afraid I am away from a computer the next couple of days but I'll take a look when I get back.
> 
> That being said, my hunch is that the test is panicking somewhere, and this is getting lost as the log facade isn't initialised. Perhaps you might test this out?
> 
> (As an aside fixing I'll add fixing the lack of panic guards to my list)

Yeah, I can take a look

**Comment by thinkharderdev** [comment]
K,  I think it's fixed. We have to treat `CoalesceBatchExec` as a repartition pipeline since it will eagerly poll it's input.

**Comment by tustvold** [comment]
Hmm... That should just work... Something isn't quite right here... FWIW CoalesceBatches is not a repartition operation, it stitches batches together within a partition, so this PR currently will change the behaviour of the plan

**Comment by thinkharderdev** [comment]
K, looked some more and I think the issue is that the output channel closes as soon as any output partition finishes. Pushed a change that will track the active output partitions and close the output channel only if all partitions are done.

**Comment by tustvold** [comment]
Ahah! Yeah that would do it, thanks for investigating 👍

**Comment by tustvold** [comment]
I fixed this as part of supporting partitioned execution - see https://github.com/apache/arrow-datafusion/pull/2226/commits/505e880ad5d3a3e1714c98942ce207959ab3f2d1

In particular a reduced version of this test case can be found https://github.com/apache/arrow-datafusion/pull/2226/commits/505e880ad5d3a3e1714c98942ce207959ab3f2d1#diff-0005c0590888cdd2c7efd378972ade4f764ec75f4c62e009eb863e4a2bef99f9R378

**Pull request closed without merging**
